### ISSUE TITLE
При вводе вырыжения с отрицательным результатом добавляется отрицательный доход.

### ISSUE THREAD

**Issue by o-ee** [Bartholomeow/moneycalc#2]
1. Открываем окно добавления доходов.
2. Вводим выражение, в результате которого получается отрицательное число.
3. Нажимаем добавить и смотрим результат.
4. Добавляется отрицательный доход.

![Снимок экрана (78)](https://user-images.githubusercontent.com/56483035/71095843-57471300-21be-11ea-85d1-0ddf1ad661f8.png)
![Снимок экрана (79)](https://user-images.githubusercontent.com/56483035/71095845-57471300-21be-11ea-9692-bd3696bf5beb.png)

**Comment by Bartholomeow** [comment]
Исправлено.
