### ISSUE TITLE
Текст не помещается в окне *Добавить категорию*

### ISSUE THREAD

**Issue by smailuly** [Bartholomeow/moneycalc#3]
Шрифт и размер диалоговых окон не маштабируется в зависимости от разрешения экрана, вследствие чего текст не помещается в окне и в поле ввода категории

Прилагаю скриншот програмы при разрешении экрана 1600 на 900
![image](https://user-images.githubusercontent.com/55974106/71310318-da1cd780-2423-11ea-8eb2-6da15ef47bf5.png)

**Comment by Bartholomeow** [comment]
Криво, но исправлено.
