### ISSUE TITLE
Ошибка при вводе больших сумм

### ISSUE THREAD

**Issue by smailuly** [Bartholomeow/moneycalc#4]
Программа: BudgetManager.exe
Ошибка расчета баланса при вводе больших сумм

Скриншот программы при вводе дохода 9000000000
Ожидание; баланс:  9000000000 руб
![image](https://user-images.githubusercontent.com/55974106/71310754-b019e400-2428-11ea-90f2-d1b04184572f.png)

Скриншот программы при вводе расхода 5000000000
Ожидание; баланс:  -5000000000 руб
![image](https://user-images.githubusercontent.com/55974106/71310800-64b40580-2429-11ea-941c-c41420c921fc.png)

**Comment by Bartholomeow** [comment]
Вроде исправлено.
